apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-new-service
  labels:
    name: my-flask-app
spec:
  selector:
    app: my-flask-app
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 5000
      protocol: TCP